/* AUTO-GENERATED by KarcinoJen synthesize.py — DO NOT EDIT */
/* Generated: 2026-04-16T06:18:06.054837+00:00 */
#include "driver.h"

/* USART2 — CR1 */
void usart2_cr1_init(void) {
    /* TODO: configure CR1 for your application */
}

uint32_t usart2_cr1_read(void) {
    return *((volatile uint32_t *)USART2_CR1_ADDR);
}

void usart2_cr1_write(uint32_t val) {
    *((volatile uint32_t *)USART2_CR1_ADDR) = val;
}
