/* AUTO-GENERATED by KarcinoJen synthesize.py — DO NOT EDIT */
/* Generated: 2026-04-16T06:21:49.920478+00:00 */
#ifndef DRIVER_H
#define DRIVER_H

#include <stdint.h>

/* ── Register Addresses and Bit-Field Macros ─────── */

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : USART_CR1
 * MCU Family : MockMCU
 * Source     : mock_fixture.pdf  page-id: fixture_q1
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define USART2_USART_CR1_ADDR                            0x40004400UL
#define USART2_USART_CR1_UE_POS                          0U   /* RW | width=1 */
#define USART2_USART_CR1_UE_MASK                         0x00000001UL
#define USART2_USART_CR1_RE_POS                          2U   /* RW | width=1 */
#define USART2_USART_CR1_RE_MASK                         0x00000004UL
#define USART2_USART_CR1_TE_POS                          3U   /* RW | width=1 */
#define USART2_USART_CR1_TE_MASK                         0x00000008UL

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : USART_CR1
 * MCU Family : MockMCU
 * Source     : mock_fixture.pdf  page-id: fixture_q2
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define USART2_USART_CR1_ADDR                            0x40004400UL
#define USART2_USART_CR1_UE_POS                          0U   /* RW | width=1 */
#define USART2_USART_CR1_UE_MASK                         0x00000001UL

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : USART_CR1
 * MCU Family : MockMCU
 * Source     : mock_fixture.pdf  page-id: fixture_q3
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define USART2_USART_CR1_ADDR                            0x40004400UL
#define USART2_USART_CR1_UE_POS                          0U   /* RW | width=1 */
#define USART2_USART_CR1_UE_MASK                         0x00000001UL
#define USART2_USART_CR1_M1_POS                          28U   /* RW | width=1 */
#define USART2_USART_CR1_M1_MASK                         0x10000000UL

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : USART_CR1
 * MCU Family : MockMCU
 * Source     : mock_fixture.pdf  page-id: fixture_q4
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define USART2_USART_CR1_ADDR                            0x40004400UL
#define USART2_USART_CR1_UE_POS                          0U   /* RW | width=1 */
#define USART2_USART_CR1_UE_MASK                         0x00000001UL

/* ----------------------------------------------------------------------
 * Peripheral : I2C1
 * Register   : I2C_CR1
 * MCU Family : MockMCU
 * Source     : mock_fixture.pdf  page-id: fixture_q5
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define I2C1_I2C_CR1_ADDR                                0x40005400UL
#define I2C1_I2C_CR1_PE_POS                              0U   /* RW | width=1 */
#define I2C1_I2C_CR1_PE_MASK                             0x00000001UL

/* ── Function Declarations ──────────────────────── */

void     usart2_usart_cr1_init(void);
uint32_t usart2_usart_cr1_read(void);
void     usart2_usart_cr1_write(uint32_t val);

void     usart2_usart_cr1_init(void);
uint32_t usart2_usart_cr1_read(void);
void     usart2_usart_cr1_write(uint32_t val);

void     usart2_usart_cr1_init(void);
uint32_t usart2_usart_cr1_read(void);
void     usart2_usart_cr1_write(uint32_t val);

void     usart2_usart_cr1_init(void);
uint32_t usart2_usart_cr1_read(void);
void     usart2_usart_cr1_write(uint32_t val);

void     i2c1_i2c_cr1_init(void);
uint32_t i2c1_i2c_cr1_read(void);
void     i2c1_i2c_cr1_write(uint32_t val);

#endif /* DRIVER_H */
