/* AUTO-GENERATED by KarcinoJen synthesize.py — DO NOT EDIT */
/* Generated: 2026-04-16T06:21:49.921487+00:00 */
#include "driver.h"

/* USART2 — USART_CR1 */
void usart2_usart_cr1_init(void) {
    /* TODO: configure USART_CR1 for your application */
}

uint32_t usart2_usart_cr1_read(void) {
    return *((volatile uint32_t *)USART2_USART_CR1_ADDR);
}

void usart2_usart_cr1_write(uint32_t val) {
    *((volatile uint32_t *)USART2_USART_CR1_ADDR) = val;
}

/* USART2 — USART_CR1 */
void usart2_usart_cr1_init(void) {
    /* TODO: configure USART_CR1 for your application */
}

uint32_t usart2_usart_cr1_read(void) {
    return *((volatile uint32_t *)USART2_USART_CR1_ADDR);
}

void usart2_usart_cr1_write(uint32_t val) {
    *((volatile uint32_t *)USART2_USART_CR1_ADDR) = val;
}

/* USART2 — USART_CR1 */
void usart2_usart_cr1_init(void) {
    /* TODO: configure USART_CR1 for your application */
}

uint32_t usart2_usart_cr1_read(void) {
    return *((volatile uint32_t *)USART2_USART_CR1_ADDR);
}

void usart2_usart_cr1_write(uint32_t val) {
    *((volatile uint32_t *)USART2_USART_CR1_ADDR) = val;
}

/* USART2 — USART_CR1 */
void usart2_usart_cr1_init(void) {
    /* TODO: configure USART_CR1 for your application */
}

uint32_t usart2_usart_cr1_read(void) {
    return *((volatile uint32_t *)USART2_USART_CR1_ADDR);
}

void usart2_usart_cr1_write(uint32_t val) {
    *((volatile uint32_t *)USART2_USART_CR1_ADDR) = val;
}

/* I2C1 — I2C_CR1 */
void i2c1_i2c_cr1_init(void) {
    /* TODO: configure I2C_CR1 for your application */
}

uint32_t i2c1_i2c_cr1_read(void) {
    return *((volatile uint32_t *)I2C1_I2C_CR1_ADDR);
}

void i2c1_i2c_cr1_write(uint32_t val) {
    *((volatile uint32_t *)I2C1_I2C_CR1_ADDR) = val;
}
