/* AUTO-GENERATED by KarcinoJen synthesize.py — DO NOT EDIT */
/* Generated: 2026-04-16T06:20:25.909625+00:00 */
#ifndef DRIVER_H
#define DRIVER_H

#include <stdint.h>

/* ── Register Addresses and Bit-Field Macros ─────── */

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : CR1
 * MCU Family : STM32F401
 * Source     : stm32f401-rm.pdf  page-id: stm32f401_rm_p551
 * Validated  : PASS  (attempts: 2)
 * ---------------------------------------------------------------------- */
#define USART2_CR1_ADDR                                  0x40005400UL
#define USART2_CR1_UE_POS                                13U   /* RW | width=1 */
#define USART2_CR1_UE_MASK                               0x00002000UL
#define USART2_CR1_M_POS                                 12U   /* RW | width=1 */
#define USART2_CR1_M_MASK                                0x00001000UL
#define USART2_CR1_PCE_POS                               10U   /* RW | width=1 */
#define USART2_CR1_PCE_MASK                              0x00000400UL
#define USART2_CR1_TE_POS                                3U   /* RW | width=1 */
#define USART2_CR1_TE_MASK                               0x00000008UL
#define USART2_CR1_RE_POS                                2U   /* RW | width=1 */
#define USART2_CR1_RE_MASK                               0x00000004UL

/* ── Function Declarations ──────────────────────── */

void     usart2_cr1_init(void);
uint32_t usart2_cr1_read(void);
void     usart2_cr1_write(uint32_t val);

#endif /* DRIVER_H */
