/* AUTO-GENERATED by KarcinoJen synthesize.py — DO NOT EDIT */
/* Generated: 2026-04-15T20:14:12.313856+00:00 */
#include "driver.h"

/* USART2 — USART_CR1 */
void usart2_usart_cr1_init(void) {
    /* TODO: configure USART_CR1 for your application */
}

uint32_t usart2_usart_cr1_read(void) {
    return *((volatile uint32_t *)USART2_USART_CR1_ADDR);
}

void usart2_usart_cr1_write(uint32_t val) {
    *((volatile uint32_t *)USART2_USART_CR1_ADDR) = val;
}

/* USART2 — USART_BRR */
void usart2_usart_brr_init(void) {
    /* TODO: configure USART_BRR for your application */
}

uint32_t usart2_usart_brr_read(void) {
    return *((volatile uint32_t *)USART2_USART_BRR_ADDR);
}

void usart2_usart_brr_write(uint32_t val) {
    *((volatile uint32_t *)USART2_USART_BRR_ADDR) = val;
}

/* GPIOA — GPIOA_MODER */
void gpioa_moder_init(void) {
    /* TODO: configure GPIOA_MODER for your application */
}

uint32_t gpioa_moder_read(void) {
    return *((volatile uint32_t *)GPIOA_MODER_ADDR);
}

void gpioa_moder_write(uint32_t val) {
    *((volatile uint32_t *)GPIOA_MODER_ADDR) = val;
}
