/* AUTO-GENERATED by KarcinoJen synthesize.py — DO NOT EDIT */
/* Generated: 2026-04-15T20:14:12.313001+00:00 */
#ifndef DRIVER_H
#define DRIVER_H

#include <stdint.h>

/* ── Register Addresses and Bit-Field Macros ─────── */

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : USART_CR1
 * MCU Family : STM32L4
 * Source     : RM0351.pdf  page-id: stm32l4_rm0351_p1238
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define USART2_USART_CR1_ADDR                            0x40004400UL
#define USART2_USART_CR1_UE_POS                          0U   /* RW | width=1 */
#define USART2_USART_CR1_UE_MASK                         0x00000001UL
#define USART2_USART_CR1_RE_POS                          2U   /* RW | width=1 */
#define USART2_USART_CR1_RE_MASK                         0x00000004UL
#define USART2_USART_CR1_TE_POS                          3U   /* RW | width=1 */
#define USART2_USART_CR1_TE_MASK                         0x00000008UL
#define USART2_USART_CR1_IDLEIE_POS                      4U   /* RW | width=1 */
#define USART2_USART_CR1_IDLEIE_MASK                     0x00000010UL
#define USART2_USART_CR1_RXNEIE_POS                      5U   /* RW | width=1 */
#define USART2_USART_CR1_RXNEIE_MASK                     0x00000020UL
#define USART2_USART_CR1_TCIE_POS                        6U   /* RW | width=1 */
#define USART2_USART_CR1_TCIE_MASK                       0x00000040UL
#define USART2_USART_CR1_TXEIE_POS                       7U   /* RW | width=1 */
#define USART2_USART_CR1_TXEIE_MASK                      0x00000080UL
#define USART2_USART_CR1_M0_POS                          12U   /* RW | width=1 */
#define USART2_USART_CR1_M0_MASK                         0x00001000UL
#define USART2_USART_CR1_OVER8_POS                       15U   /* RW | width=1 */
#define USART2_USART_CR1_OVER8_MASK                      0x00008000UL

/* ----------------------------------------------------------------------
 * Peripheral : USART2
 * Register   : USART_BRR
 * MCU Family : STM32L4
 * Source     : RM0351.pdf  page-id: stm32l4_rm0351_p1241
 * Validated  : PASS  (attempts: 1)
 * ---------------------------------------------------------------------- */
#define USART2_USART_BRR_ADDR                            0x4000440CUL
#define USART2_USART_BRR_BRR_POS                         0U   /* RW | width=16 */
#define USART2_USART_BRR_BRR_MASK                        0x0000FFFFUL

/* ----------------------------------------------------------------------
 * Peripheral : GPIOA
 * Register   : GPIOA_MODER
 * MCU Family : STM32L4
 * Source     : RM0351.pdf  page-id: stm32l4_rm0351_p303
 * Validated  : PASS  (attempts: 2)
 * ---------------------------------------------------------------------- */
#define GPIOA_MODER_ADDR                                 0x48000000UL
#define GPIOA_MODER_MODER0_POS                           0U   /* RW | width=2 */
#define GPIOA_MODER_MODER0_MASK                          0x00000003UL
#define GPIOA_MODER_MODER1_POS                           2U   /* RW | width=2 */
#define GPIOA_MODER_MODER1_MASK                          0x0000000CUL
#define GPIOA_MODER_MODER2_POS                           4U   /* RW | width=2 */
#define GPIOA_MODER_MODER2_MASK                          0x00000030UL
#define GPIOA_MODER_MODER15_POS                          30U   /* RW | width=2 */
#define GPIOA_MODER_MODER15_MASK                         0xC0000000UL

/* ── Function Declarations ──────────────────────── */

void     usart2_usart_cr1_init(void);
uint32_t usart2_usart_cr1_read(void);
void     usart2_usart_cr1_write(uint32_t val);

void     usart2_usart_brr_init(void);
uint32_t usart2_usart_brr_read(void);
void     usart2_usart_brr_write(uint32_t val);

void     gpioa_moder_init(void);
uint32_t gpioa_moder_read(void);
void     gpioa_moder_write(uint32_t val);

#endif /* DRIVER_H */
